<a href="https://colab.research.google.com/github/codingwithsubhransu/Machine-Learning-Course/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy - Numerical Python

In [ ]:
import numpy as np

In [ ]:
from time import process_time

Time battle between list and numpy array

In [ ]:
python_list = [i for i in range(100000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

4.930510669


In [ ]:
np_array = np.array([i for i in range(100000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.09080628699999949


Numpy Arrays

In [ ]:
l1 = [1,2,3,4,5]
print(l1)
type(l1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
np_array.shape

(5,)

In [ ]:
np_array = np.array([[1,2,3],[4,5,6]])
print(np_array)
type(np_array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
np_array.shape

(2, 3)

In [ ]:
np_arr = np.array([1,2,4,5], dtype=float)
print(np_arr)

[1. 2. 4. 5.]


Initial Placeholders in numpy arrays

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y= np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z= np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
b = np.random.random((3, 4))
print(b)

[[0.80769359 0.67218421 0.82070937 0.8232392 ]
 [0.82004442 0.2824496  0.31239517 0.39362105]
 [0.67405155 0.73041061 0.36590655 0.88441457]]


In [ ]:
c = np.random.randint(10, 12, (3, 5))
print(c)

[[10 11 10 10 11]
 [11 10 10 10 10]
 [11 11 11 11 10]]


In [ ]:
d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [ ]:
l2 = [1,2,3,4,5]
np_array = np.asarray(l2)
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10, 90, (5, 5))
print(c)

[[65 85 58 51 69]
 [37 65 27 15 36]
 [59 72 49 84 63]
 [62 11 21 23 51]
 [35 28 48 78 28]]


In [ ]:
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(5, 5)
2
25
int64


Mathematical Operation in a np array

In [ ]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))
print(a)
print(b)

[[0 3 7]
 [1 5 2]
 [2 5 3]]
[[10 12 14]
 [10 13 10]
 [11 18 13]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[10 15 21]
 [11 18 12]
 [13 23 16]]
[[-10  -9  -7]
 [ -9  -8  -8]
 [ -9 -13 -10]]
[[ 0 36 98]
 [10 65 20]
 [22 90 39]]
[[0.         0.25       0.5       ]
 [0.1        0.38461538 0.2       ]
 [0.18181818 0.27777778 0.23076923]]


In [ ]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[10 15 21]
 [11 18 12]
 [13 23 16]]
[[-10  -9  -7]
 [ -9  -8  -8]
 [ -9 -13 -10]]
[[ 0 36 98]
 [10 65 20]
 [22 90 39]]
[[0.         0.25       0.5       ]
 [0.1        0.38461538 0.2       ]
 [0.18181818 0.27777778 0.23076923]]


Array Manipulation

In [ ]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[1 4 1]
 [0 1 2]]
(2, 3)


In [ ]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 0]
 [4 1]
 [1 2]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 0]
 [4 1]
 [1 2]]
(3, 2)


In [ ]:
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[1 7 0]
 [0 1 0]]
(2, 3)


In [ ]:
b = a.reshape(3, 2)
print(b)
print(b.shape)

[[1 7]
 [0 0]
 [1 0]]
(3, 2)
